@host=http://localhost:3000

### GET ALL USERS
GET {{host}}/users

### REGISTER USER
POST {{host}}/register
Content-Type: application/json

{
  "email": "jankypete3000@gmail.com",
  "password": "OgresAreLikeOnions1!"
}

### LOGIN
# @name login
POST {{host}}/login
Content-Type: application/json

{
  "email": "jankypete3000@gmail.com",
  "password": "OgresAreLikeOnions1!"
}

### GET ALL CARS ON LOT
GET {{host}}/cars-on-lot

### GET SPECIFIC CAR ON LOT
GET {{host}}/cars-on-lot/1

### CREATE WATCHLIST (ADD FIRST CAR TO WATCHLIST)
POST {{host}}/watchlists
Content-Type: application/json

{
  "userID": 3,
  "carID": 2
}

### ADD CAR TO WATCHLIST
@token = {{login.response.body.token}}
POST {{host}}/watchlists/8
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "carID": 8
}

### DELETE CAR FROM WATCHLIST
@token ={{login.response.body.token}}
DELETE {{host}}/watchlists/8
Authorization: Bearer {{token}}
Content-Type: application/json

### GET SPECIFIC WATCHLIST
GET {{host}}/watchlists/5

### GREATE NEW MAKE
POST {{host}}/makes
Content-Type: application/json

{
  "name": "Porsche",
  "description": "Porsche is a renowned German automobile brand celebrated for its high-performance sports cars, SUVs, and sedans all known for their engineering excellence, sleek designs, and unparalleled driving experiences. The brand has cultivated a reputation for merging luxury with cutting-edge technology, making it a favorite among car enthusiasts. Models like the iconic 911, the versatile Cayenne, and the dynamic Taycan showcase Porsche's commitment to innovation and automotive artistry."
}

### CREATE NEW MODEL
POST {{host}}/models
Content-Type: application/json

{
  "name": "911",
  "makeName": "Porsche"
}

### CREATE NEW CAR ON LOT
POST {{host}}/cars-on-lot
Content-Type: application/json

{
  "headline": "Top of the Line 2024 Chevy Camaro",
  "description": "Experience the power and luxury of the 2024 Chevy Camaro with the latest features and technology.",
  "image": "https://content.homenetiol.com/e5770a7a3d964049ae21b10a8a737b89.jpg",
  "year": 2024,
  "miles": 5800,
  "drivetrain": "RWD",
  "engine": "6.2L V8",
  "color": "Red",
  "MPG_city": 16,
  "MPG_highway": 24,
  "modelId": 2,
  "features": [
    "Heated seats",
    "Navigation system",
    "Backup camera",
    "Bluetooth connectivity",
    "Premium sound system"
  ],
  "price": 72000
}