  // const createTestCars = () => {
  // const allMakes = await prisma.make.findMany();  
  // const allModels = await prisma.model.findMany();

  const testCars = [
    {
      headline: "Brand New ZR1 Corvette",
      description: "This is a test car for use in site development.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 2025,
      miles: 4,
      drivetrain: "RWD",
      engine: "6.2L V8",
      color: "Black",
      MPG_city: 16,
      MPG_highway: 25,
      makeName: "Chevrolet",
      modelName: "Corvette",
      features: [
        "ZR1 Package",
        "Advanced Infotainment System",
        "Wireless Smartphone Charging",
        "Heads-Up Display",
        "Premium Bose Sound System",
        "Surround-View Camera",
        "Smart Keyless Entry",
        "Customizable Ambient Lighting",
        "Heated and Ventilated Seats",
        "Leather Upholstery",
        "Carbon Fiber Interior Trim",
        "Memory Seat Settings",
        "Dual-Zone Climate Control",
        "Automatic Dimming Rearview Mirror",
        "Enhanced Navigation System",
        "Adaptive Cruise Control",
        "Remote Start",
        "Digital Instrument Cluster",
        "Rear Cross Traffic Alert",
        "Apple CarPlay and Android Auto",
        "Wi-Fi Hotspot",
        "Blind Spot Monitoring",
        "Advanced Parking Assist",
        "19-inch Alloy Wheels",
        "Premium Paint Options",
        "LED Headlights and Taillights",
        "Blackout Appearance Package"
      ],
      price: 194999 
    },
    {
      headline: "Classic 1967 Corvette Sting Ray",
      description: "A classic Corvette from the 1960s.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 1967,
      miles: 78000,
      drivetrain: "RWD",
      engine: "5.3L V8",
      color: "Red",
      MPG_city: 11,
      MPG_highway: 16,
      makeName: "Chevrolet",
      modelName: "Corvette",
      features: [
        "Manual Transmission",
        "AM/FM Radio",
        "Vinyl Interior"
      ],
      price: 79999
    },
    {
      headline: "2014 Corvette Stingray",
      description: "A modern Corvette with advanced technology.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 2014,
      miles: 32000,
      drivetrain: "RWD",
      engine: "6.2L V8",
      color: "Blue",
      MPG_city: 17,
      MPG_highway: 29,
      makeName: "Chevrolet",
      modelName: "Corvette",
      features: [
        "Automatic Transmission",
        "Touchscreen Infotainment System",
        "Leather Seats",
        "Rearview Camera",
        "Heated Seats",
        "Bluetooth Connectivity",
        "Premium Sound System",
        "Navigation System",
        "Keyless Entry and Start"
      ],
      price: 43999
    },
    {
      headline: "2018 Chevrolet Camaro SS",
      description: "A powerful modern Camaro with advanced features.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 2018,
      miles: 25000,
      drivetrain: "RWD",
      engine: "6.2L V8",
      color: "Yellow",
      MPG_city: 16,
      MPG_highway: 25,
      makeName: "Chevrolet",
      modelName: "Camaro",
      features: [
        "Automatic Transmission",
        "Touchscreen Infotainment System",
        "Leather Seats",
        "Rearview Camera",
        "Heated and Ventilated Seats",
        "Bluetooth Connectivity",
        "Premium Sound System",
        "Navigation System",
        "Keyless Entry and Start",
        "Heads-Up Display",
        "Performance Suspension",
        "20-inch Alloy Wheels",
        "LED Headlights",
        "Wireless Smartphone Charging",
        "Blind Spot Monitoring",
        "Apple CarPlay and Android Auto"
      ],
      price: 35999
    },
    {
      headline: "1970 Chevrolet Camaro Z28",
      description: "A classic Camaro from the golden era of muscle cars.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 1970,
      miles: 65000,
      drivetrain: "RWD",
      engine: "5.7L V8",
      color: "Green",
      MPG_city: 10,
      MPG_highway: 15,
      makeName: "Chevrolet",
      modelName: "Camaro",
      features: [
        "Manual Transmission",
        "AM/FM Radio",
        "Vinyl Seats",
        "Performance Exhaust",
        "15-inch Rally Wheels",
        "Front Splitter",
        "Rear Spoiler"
      ],
      price: 54999
    },
    {
      headline: "2022 Acura NSX Type S",
      description: "A high-performance hybrid supercar with advanced technology.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 2022,
      miles: 5000,
      drivetrain: "AWD",
      engine: "3.5L V6 Twin-Turbo Hybrid",
      color: "Valencia Red Pearl",
      MPG_city: 21,
      MPG_highway: 22,
      makeName: "Acura",
      modelName: "NSX",
      features: [
        "Automatic Transmission",
        "Touchscreen Infotainment System",
        "Leather and Alcantara Seats",
        "Rearview Camera",
        "Heated Seats",
        "Bluetooth Connectivity",
        "Premium Sound System",
        "Navigation System",
        "Keyless Entry and Start",
        "Carbon Ceramic Brakes",
        "Electric Power Steering",
        "Adaptive Suspension",
        "Carbon Fiber Roof",
        "Sport+ Mode",
        "Blind Spot Monitoring",
        "Apple CarPlay and Android Auto",
        "Wireless Smartphone Charging"
      ],
      price: 169999
    },
    {
      headline: "1995 Acura NSX-T",
      description: "A classic NSX with timeless design and performance.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 1995,
      miles: 45000,
      drivetrain: "RWD",
      engine: "3.0L V6",
      color: "Berlina Black",
      MPG_city: 17,
      MPG_highway: 23,
      makeName: "Acura",
      modelName: "NSX",
      features: [
        "Manual Transmission",
        "AM/FM Radio",
        "Leather Seats",
        "Air Conditioning",
        "Power Windows",
        "Power Door Locks",
        "Cruise Control",
        "16-inch Alloy Wheels",
        "Flip-Up Headlights"
      ],
      price: 74999
    },
    {
      headline: "2017 Acura NSX",
      description: "A modern hybrid supercar with cutting-edge technology.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 2017,
      miles: 18000,
      drivetrain: "AWD",
      engine: "3.5L V6 Twin-Turbo Hybrid",
      color: "Nouvelle Blue Pearl",
      MPG_city: 21,
      MPG_highway: 22,
      makeName: "Acura",
      modelName: "NSX",
      features: [
        "Automatic Transmission",
        "Touchscreen Infotainment System",
        "Leather Seats",
        "Rearview Camera",
        "Heated Seats",
        "Bluetooth Connectivity",
        "Premium Sound System",
        "Navigation System",
        "Keyless Entry and Start",
        "Carbon Ceramic Brakes",
        "Electric Power Steering",
        "Adaptive Suspension",
        "Carbon Fiber Interior Trim",
        "Sport+ Mode",
        "Blind Spot Monitoring",
        "Apple CarPlay and Android Auto",
        "Wireless Smartphone Charging"
      ],
      price: 139999
    },
    {
      headline: "2023 Acura Integra A-Spec",
      description: "A modern compact luxury sedan with sporty features.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 2023,
      miles: 1500,
      drivetrain: "FWD",
      engine: "1.5L Turbocharged I4",
      color: "Platinum White Pearl",
      MPG_city: 26,
      MPG_highway: 36,
      makeName: "Acura",
      modelName: "Integra",
      features: [
        "Automatic Transmission",
        "Touchscreen Infotainment System",
        "Leather Seats",
        "Rearview Camera",
        "Heated Seats",
        "Bluetooth Connectivity",
        "Premium Sound System",
        "Navigation System",
        "Keyless Entry and Start",
        "Adaptive Cruise Control",
        "Blind Spot Monitoring",
        "Apple CarPlay and Android Auto",
        "Wireless Smartphone Charging"
      ],
      price: 31999
    },
    {
      headline: "2001 Acura Integra Type R",
      description: "A legendary high-performance hatchback with a cult following.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 2001,
      miles: 85000,
      drivetrain: "FWD",
      engine: "1.8L I4",
      color: "Phoenix Yellow",
      MPG_city: 25,
      MPG_highway: 30,
      makeName: "Acura",
      modelName: "Integra",
      features: [
        "Manual Transmission",
        "AM/FM Radio",
        "Cloth Seats",
        "Air Conditioning",
        "Power Windows",
        "Power Door Locks",
        "Cruise Control",
        "16-inch Alloy Wheels"
      ],
      price: 24999
    },
    {
      headline: "1996 Acura Integra GS-R",
      description: "A popular sports coupe with a balance of performance and comfort.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 1996,
      miles: 97000,
      drivetrain: "FWD",
      engine: "1.8L I4",
      color: "Milano Red",
      MPG_city: 24,
      MPG_highway: 31,
      makeName: "Acura",
      modelName: "Integra",
      features: [
        "Manual Transmission",
        "AM/FM Radio",
        "Leather Seats",
        "Power Sunroof",
        "Air Conditioning",
        "Power Windows",
        "Power Door Locks",
        "Cruise Control",
        "15-inch Alloy Wheels"
      ],
      price: 17999
    },
    {
      headline: "2021 Audi A8 L",
      description: "A luxurious full-size sedan with advanced technology.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 2021,
      miles: 15000,
      drivetrain: "AWD",
      engine: "3.0L V6 Turbocharged",
      color: "Mythos Black Metallic",
      MPG_city: 17,
      MPG_highway: 26,
      makeName: "Audi",
      modelName: "A8",
      features: [
        "Automatic Transmission",
        "Touchscreen Infotainment System",
        "Leather Seats",
        "Rearview Camera",
        "Heated and Ventilated Seats",
        "Bluetooth Connectivity",
        "Premium Sound System",
        "Navigation System",
        "Keyless Entry and Start",
        "Adaptive Cruise Control",
        "Blind Spot Monitoring",
        "Apple CarPlay and Android Auto",
        "Wireless Smartphone Charging",
        "Panoramic Sunroof",
        "LED Headlights",
        "Massage Seats",
        "Air Suspension",
        "Head-Up Display"
      ],
      price: 76999
    },
    {
      headline: "2018 Audi A8 L",
      description: "A previous generation of the luxurious full-size sedan.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 2018,
      miles: 45000,
      drivetrain: "AWD",
      engine: "4.0L V8 Turbocharged",
      color: "Moonlight Blue Metallic",
      MPG_city: 15,
      MPG_highway: 24,
      makeName: "Audi",
      modelName: "A8",
      features: [
        "Automatic Transmission",
        "Touchscreen Infotainment System",
        "Leather Seats",
        "Rearview Camera",
        "Heated and Ventilated Seats",
        "Bluetooth Connectivity",
        "Premium Sound System",
        "Navigation System",
        "Keyless Entry and Start",
        "Adaptive Cruise Control",
        "Blind Spot Monitoring",
        "Apple CarPlay and Android Auto",
        "Wireless Smartphone Charging",
        "Panoramic Sunroof",
        "LED Headlights",
        "Massage Seats",
        "Air Suspension",
        "Night Vision Assist"
      ],
      price: 62999
    },
    {
      headline: "2022 Toyota Tundra TRD Pro",
      description: "A rugged full-size pickup truck with off-road capabilities.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 2022,
      miles: 12000,
      drivetrain: "4WD",
      engine: "3.5L V6 Twin-Turbo",
      color: "Lunar Rock",
      MPG_city: 17,
      MPG_highway: 23,
      makeName: "Toyota",
      modelName: "Tundra",
      features: [
        "Automatic Transmission",
        "Touchscreen Infotainment System",
        "Leather Seats",
        "Rearview Camera",
        "Heated and Ventilated Seats",
        "Bluetooth Connectivity",
        "Premium Sound System",
        "Navigation System",
        "Keyless Entry and Start",
        "Adaptive Cruise Control",
        "Blind Spot Monitoring",
        "Apple CarPlay and Android Auto",
        "Wireless Smartphone Charging",
        "Off-Road Suspension",
        "Skid Plates",
        "LED Headlights",
        "Tow Package",
        "Panoramic Sunroof"
      ],
      price: 59999
    },
    {
      headline: "2018 Toyota Tundra Limited",
      description: "A reliable full-size pickup truck with luxurious features.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 2018,
      miles: 45000,
      drivetrain: "4WD",
      engine: "5.7L V8",
      color: "Midnight Black Metallic",
      MPG_city: 13,
      MPG_highway: 18,
      makeName: "Toyota",
      modelName: "Tundra",
      features: [
        "Automatic Transmission",
        "Touchscreen Infotainment System",
        "Leather Seats",
        "Rearview Camera",
        "Heated Seats",
        "Bluetooth Connectivity",
        "Premium Sound System",
        "Navigation System",
        "Keyless Entry and Start",
        "Adaptive Cruise Control",
        "Blind Spot Monitoring",
        "Apple CarPlay and Android Auto",
        "Wireless Smartphone Charging",
        "LED Headlights",
        "Tow Package",
        "Fog Lights"
      ],
      price: 43999
    },                     
    {
      headline: "Late Model Challenger Hellcat",
      description: "This is a test car for use in site development.",
      images: ["uploads/1738638158288-Honda_Civic_SI1.jpeg"],
      year: 2023,
      miles: 12588,
      drivetrain: "RWD",
      engine: "Supercharged 6.2L V8",
      color: "Red",
      MPG_city: 13,
      MPG_highway: 22,
      makeName: "Dodge",
      modelName: "Challenger",
      features: [
        "SRT Hellcat Package",
        "Advanced Infotainment System",
        "Heads-Up Display",
        "Smart Keyless Entry",
        "Customizable Ambient Lighting",
        "Heated and Ventilated Seats",
        "Leather Upholstery",
        "Memory Seat Settings",
        "Dual-Zone Climate Control",
        "Automatic Dimming Rearview Mirror",
        "Enhanced Navigation System",
        "Adaptive Cruise Control",
        "Remote Start",
        "Digital Instrument Cluster",
        "Rear Cross Traffic Alert",
        "Apple CarPlay and Android Auto",
        "Wi-Fi Hotspot",
        "Blind Spot Monitoring",
        "Advanced Parking Assist",
        "LED Headlights and Taillights",
      ],
      price: 92999 
    }
  ]

module.exports = testCars;

// makeName: allMakes[2].name,
// modelName: allModels[56].name,

// makeName: allMakes[4].name,
// modelName: allModels[127].name,